args = commandArgs(trailingOnly=TRUE)
train=read.csv(args[[1]])
train=data.matrix(train)
mTrain=read.csv('DATA/mean')
mTrain=data.matrix(mTrain)
sigma=read.csv('DATA/sigma')
train = train - as.vector(mTrain)
sigma=data.matrix(sigma)
train = train / as.vector(sigma)
write.csv(train,paste(args[[1]],'.norm',sep=''),row.names = FALSE)
#write.csv(train,'dump2')
